
resource_types:
# ==== misc resources ====
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: 3


resources:
# ==== concorse itself ===
- name: cs-pipelines
  type: concourse-pipeline
  source:
    # target: ${ATC_EXTERNAL_URL}
    insecure: "true" # Because docker image doesn't have valid CA certs for zlab
    teams:
    - name: main
      username: concourse
      password: changeme

# ==== repositories ====
- name: set-pipelines-pipeline
  type: git
  source:
    uri: https://github.com/yuanying/test-release.git
    branch: master


# ==== jobs ====
jobs:
- name: deploy-test-pipeline
  plan:
  - do:
    - get: set-pipelines-pipeline
      trigger: true
    - put: cs-pipelines
      params:
        pipelines:
        - name: test-pipeline
          team: main
          config_file: set-pipelines-pipeline/pipelines/test.yaml
          unpaused: true
